networks:
  geoquizz.net:
    driver: bridge

services:
  gateway.geoquizz:
    #images: 'canals/php:8.3-cli'
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '42050:80'
    volumes:
      - ./gateway:/var/php
    networks:
      - geoquizz.net
    command: php -S 0.0.0.0:80 -t /var/php/public

  geoquizz.front:
    build:
      context: build
      dockerfile: apache.Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend/dist:/var/www/html
    ports:
      - "42051:80"
    networks:
      - geoquizz.net

  geoquizz.mail:
    #images: 'canals/php:8.3-cli'
    restart: unless-stopped
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '42052:80'
    volumes:
      - ./app-mail:/var/php
      - ./rabbitmq.env:/var/.env
    working_dir: /var/php
    networks:
      - geoquizz.net
    depends_on:
      - geoquizz.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  rabbitmq:
    image: 'rabbitmq:3-management'
    restart: unless-stopped
    ports:
      - '42053:15672'
    env_file:
      - rabbitmq.env
    networks:
      - geoquizz.net

  geoquizz.db:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file: geoquizzdb.env
    ports:
      - '42054:5432'
    networks:
      - geoquizz.net
    volumes:
      - ./app/sql:/var/sql

  geoquizz.game:
    # images: 'canals/php:8.3-cli'
    restart: unless-stopped
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '42055:80'
    volumes:
      - ./app-game:/var/php
      - ./geoquizzdb.env:/var/geoquizzdb.env
      - ./dbgame.env:/var/dbgame.env
      - ./.env:/var/.env
    working_dir: /var/php
    networks:
      - geoquizz.net
    depends_on:
      - geoquizz.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  geoquizz.auth:
    #images: 'canals/php:8.3-cli'
    restart: unless-stopped
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '42056:80'
    volumes:
      - ./app-auth:/var/php
      - ./.env:/var/.env
    working_dir: /var/php
    networks:
      - geoquizz.net
    depends_on:
      - geoquizz.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  directus.db:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file: directusdb.env
    ports:
      - '42057:5432'  
    networks:
      - geoquizz.net
    volumes:
      - ./directus/data/database:/var/lib/postgresql/data 


  directus:
    image: directus/directus:latest
    container_name: directus-app
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    env_file: directus.env
    ports:
      - "42058:8055"
    networks:
      - geoquizz.net 
    depends_on:
      - directus.db
  adminer:
    image: adminer
    restart: always
    ports:
      - '42059:8080'
    command: php -S 0.0.0.0:8080 -t /var/www/html
    networks:
      - geoquizz.net


  mailcatcher:
    build:
      context: build
      dockerfile: ruby.Dockerfile
    ports:
        - '42060:1080'
        - '42061:1025'
    networks:
        - geoquizz.net

