networks:
  geoquizz.net:
    driver: bridge

services:
  gateway.geoquizz:
    #image: 'canals/php:8.3-cli'
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '42050:80'
    volumes:
      - ./gateway:/var/php
    networks:
      - geoquizz.net
    command: php -S 0.0.0.0:80 -t /var/php/public

  geoquizz.front:
    image: ubuntu/apache2:latest
    restart: unless-stopped
    ports:
      - "42053:80"
    volumes:
      - ./frontend/dist/:/var/www/html
    networks:
      - geoquizz.net.net

  qeoquizz.mail:
    image: 'canals/php:8.3-cli'
    restart: unless-stopped
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '42054:80'
    volumes:
      - ./app-mail:/var/php
    working_dir: /var/php
    networks:
      - geoquizz.net
    depends_on:
      - geoquizz.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  geoquizz.rabbitmq:
    image: 'rabbitmq:3-management'
    restart: unless-stopped
    ports:
      - '42055:15672'
    networks:
      - geoquizz.net

  geoquizz.db:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file: ./app/config/geoquizzdb.env
    ports:
      - '42051:5432'
    networks:
      - geoquizz.net
    volumes:
      - ./app/sql:/var/sql

  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '42052:8080'
    networks:
      - geoquizz.net