networks:
  geoquizz.net:
    driver: bridge

services:
  # service gateway.toubeelib : serveur web
  gateway.geoquizz:
    #image: 'canals/php:8.3-cli'
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '6081:80'
    volumes:
      - ./gateway:/var/php
    networks:
      - geoquizz.net
    depends_on:
      - api.geoquizz
    command: php -S 0.0.0.0:80 -t /var/php/public

  api.geoquizz:
    #  image: 'canals/php:8.3-cli'
    restart: unless-stopped
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - geoquizz.net
    depends_on:
      - geoquizz.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  # service toubeelib.db : base de données postgresql
  geoquizz.db:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file: ./app/config/toubeelibdb.env
    ports:
      - '5432:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./app/sql:/var/sql
  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - geoquizz.net